server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://124.222.48.211:3306/xiaomi?characterEncoding=UTF8
    username: root
    password: m5zTZNxExhFM8s7Y
  redis:
    host: localhost
  rabbitmq:
    host: localhost

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
