server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://124.222.48.211:3306/xiaomi?characterEncoding=UTF8
    username: root
    password: 123456
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true